wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706623853.281082
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 4
      - 13
      - 23
      - 37
      - 42
      4: 3.8.17
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
